### ISSUE TITLE
Create base docker image

### ISSUE THREAD

**Issue by Meharban-Singh** [UWCodeForce/student-net#2]
Once we determine the requirements for this project, we will need a base docker image that we can share so everyone can have the same dev/test environments.

The live server that will be used once code is deployed to main will be running Ubuntu 20.04 LTS, so it's probably best if docker images are based on that.

**Comment by xTrig** [comment]
[docker-student-net.zip](https://github.com/UWCodeForce/student-net/files/7255040/docker-student-net.zip)
