### ISSUE TITLE
Create Job Page for Student's

### ISSUE THREAD

**Issue by nickvichai** [UWCodeForce/student-net#4]
Two ways:
A) Create a job portal and allow employers to add jobs there.
B) Grab jobs from external sources and filter all the student jobs to add to the website.
C) Both A and B

**Comment by Meharban-Singh** [comment]
We should try both a and b. For b, we can try web scraping from some sources (like indeed etc) and try APIs for the sources that have APIs (Github jobs)

**Comment by nickvichai** [comment]
Ill do this one
