### ISSUE TITLE
Change SQL result object to remove field data

### ISSUE THREAD

**Issue by xTrig** [UWCodeForce/student-net#48]
Right now a lot of our codebase uses samples such as the one below.

```js
var results = await query('SELECT * FROM something');
```

What this does is actually return an array with our results[] inside of it, along with our field data. We don't want this, and this can cause some issues when checking if results.length > 0 (which it always will be).

We need to change all occurences to
```js
var [results] = await query('SELECT * FROM something');
```
So we strip the extra data we don't want, preventing some headaches in the future.

**Comment by Raghuboi** [comment]
will get this fixed right away
